This test did not run, because a parent test that this test depends on already gave a negative result ('fail').
